stages:
    - format
    - build
    - test

format:
    stage: format
    image: starlabio/ubuntu-native-build:1.0.12
    script:
        - cargo fmt -- --write-mode=diff

build:
    stage: build
    image: starlabio/ubuntu-native-build:1.0.12
    dependencies: []
    script:
        - cargo build --verbose
        - cargo test --verbose
    artifacts:
        expire_in: 1 week
        paths:
            - target/debug/examples/

build-device-only:
    stage: build
    image: starlabio/ubuntu-native-build:1.0.12
    dependencies: []
    script:
        - cargo build --no-default-features --features tcti-device

test:
    stage: test
    image: starlabio/tpm-emulator:2.0
    before_script:
        - tpm_server -rm &
        - sleep 3 # cause the server needs some time
        - tpm2_startup --clear
    script:
        - ./target/debug/examples/ownership
        - ./target/debug/examples/nvdefine
        - ./target/debug/examples/nvinfo
        - ./target/debug/examples/nvwrite
        - ./target/debug/examples/nvread
        - ./target/debug/examples/nvreadlock
        - ./target/debug/examples/nvrelease
